FROM alpine:latest as builder
MAINTAINER HackXiu <hakkxiu@gmail.com>

ARG NGINX_VERSION=1.16.0
ARG NGINX_RTMP_VERSION=1.2.1
ARG JEMALLOC_VER=5.2.0


RUN	apk update		&&	\
	apk add				\
		git			\
		gcc			\
		binutils		\
		gmp			\
		isl			\
		libgomp			\
		libatomic		\
		libgcc			\
		openssl			\
		pkgconf			\
		pkgconfig		\
		mpfr3			\
		mpc1			\
		libstdc++		\
		ca-certificates		\
		libssh2			\
		curl			\
		expat			\
		pcre			\
		musl-dev		\
		libc-dev		\
		pcre-dev		\
		zlib-dev		\
		openssl-dev		\
		curl			\
		make


RUN	cd /tmp/									&&	\
	curl -s --remote-name https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz			&&	\
	curl -s --remote-name https://github.com/jemalloc/jemalloc/releases/download/${JEMALLOC_VER}/jemalloc-${JEMALLOC_VER}.tar.bz2			&&	\
	git clone https://github.com/arut/nginx-rtmp-module.git -b v${NGINX_RTMP_VERSION}

RUN	cd /tmp										&&  \
	tar xzf nginx-${NGINX_VERSION}.tar.gz               &&  \
	tar xjf jemalloc-${JEMALLOC_VER}.tar.bz2               &&  \
	cd nginx-${NGINX_VERSION}							&&  \
	./configure                                          \
		--prefix=/opt/nginx                              \
		--with-http_ssl_module                           \
		--add-module=../nginx-rtmp-module                \
		--with-ld-opt='-ljemalloc'                        \
		#--with-debug                                     \
		--with-cc-opt="-Wimplicit-fallthrough=0"					&&	\
	make										&&	\
	make install                                &&	\
	cd jemalloc-${JEMALLOC_VER}                 &&	\

FROM alpine:latest
RUN apk update		&& \
	apk add			   \
		openssl		   \
		libstdc++	   \
		ca-certificates	   \
		pcre

COPY --from=0 /opt/nginx /opt/nginx
COPY --from=0 /tmp/nginx-rtmp-module/stat.xsl /opt/nginx/conf/stat.xsl
RUN rm /opt/nginx/conf/nginx.conf
ADD run.sh /

EXPOSE 1935
EXPOSE 8080

CMD /run.sh

